name: CI


on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: push to server
        uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.server_ip }}
          username: ${{ secrets.server_username }}
          password: ${{ secrets.server_password }}
          script: cd ${{ secrets.project_path }} && git fetch && git checkout ${{ steps.extract_branch.outputs.branch }} && git pull && npm i && npm run build && sudo systemctl restart nginx